(define caar (x) (car (car x)))
(define cadr (x) (car (cdr x)))
(define cdar (x) (cdr (car x)))
(define cddr (x) (cdr (cdr x)))
(set list '(1 2 3 4 5))
(cadr list)
(cddr list)
(set list '((1 2) 3 4 5))
(caar list)
(cadr list)
(cdar list)
(cddr list)
quit