(define len (l) (if (null? l) 0 (+ (len (cdr l)) 1)))
(set list '(1 2 3 4 5 6 7 8 9))
(len list)
(len (cdr list))
(set list (cdr list))
(len list)
(set list (cdr list))
(set list (cdr list))
(set list (cdr list))
(set list (cdr list))
(set list (cdr list))
(set list (cdr list))
(set list (cdr list))
(len list)
(set list (cdr list))
(len list)
quit